### PR TITLE
Scrapper, Maxim Glukhankov - 22FPL1

### PR DESCRIPTION
**Pull request by glukhankov**

### CODE REVIEW

**Comment by demid5111** [comment]
nothing to review

**Comment by demid5111** [comment]
nothing to review

**Comment by demid5111** [comment]
nothing to review

**Comment by demid5111** [comment]
nothing to review

**Comment by dmitry-uraev** [comment]
nothing to review

**Comment by marina-kaz** [comment]
Nothing to review today

**Comment by marina-kaz** [comment]
Nothing to review today

**Comment by marina-kaz** [comment]
Nothing to review today

**Comment by marina-kaz** [comment]
Nothing to review today

**Comment by marina-kaz** [comment]
No changes for me to review.

**Pull request closed without merging**
